### ISSUE TITLE
Clarify the orientation of pixel level plots

### ISSUE THREAD

**Issue by orionlee** [noraeisner/LATTE#25]
It'd be great if the orientation of pixel level plots can be clarified.
It seems that the pixels plotted upside down: with CCD rows running from smallest to largest (largest row number at the bottom).

E.g., for a report from TIC 294272049 sector 28, I got the following that shows the dip comes from pixels at the bottom:

![image](https://user-images.githubusercontent.com/250644/97095791-b6fd1e80-1618-11eb-8d43-3da0dbc1ef1a.png)

![image](https://user-images.githubusercontent.com/250644/97095794-cbd9b200-1618-11eb-9a3d-a5f8d207e855.png)

I was stumped a bit when they don't seem to match what I observed from `lightkurve`, which showed the dips come from the pixels at the top.

![image](https://user-images.githubusercontent.com/250644/97095807-f461ac00-1618-11eb-92b7-fcb1ed9df073.png)

Comparing them (and also check the aperture plot from `lightkurve`), I realized while `lightkurve` plots with CCD rows starting from largest to smallest (i.e., smallest row number at the bottom), LATTE plots it the other way, with the largest row number at the bottom).

It'd be great if this can be clarified, e.g., if LATTE consistently plots the pixels in such a way. Alternatively, if the plots include pixel row / column numbers, any confusion can be avoided as well.

**Comment by noraeisner** [comment]
Thanks for the suggestion - labelling the pixels would definitely be useful. I have updated the code such that the first and last pixel of the column and rows are labeled (I want to avoid labelling all of the pixels so that it doesn't become too cluttered). I've also rotated the tpf images such that the pixels increase from left to right and bottom to top (in line with what lightkurve does). 

![55525572_individual_pixel_LCs_1](https://user-images.githubusercontent.com/43934902/97188926-57cc1500-17a4-11eb-916b-24e4ef0c7167.png)
